version: '3'

services:
    zentao:
        image: chaiyd/zentao:12.5.3
        ports:
            - 9080:80
        volumes:
          - zentao-data:/app/zentaopms #该目录为禅道目录，里面包含禅道代码及附件上传目录。
        depends_on:
            - mysql
        restart: always

    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: ukC2ZkcG_ZTeb
            MYSQL_DATABASE: zentao
            MYSQL_USER: zentao
            MYSQL_PASSWORD: ukC2ZkcG_ZTeb
        ports:
          - 3306:3306            
        volumes:
          - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
  zentao-data:
